language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

script: pytest

deploy:
  provider: pypi
  user: maxpowel
  password:
    secure: wd6QsPoZDIZQINsrqO1lUDvwwKvihcrgmcODToCnmtTvqaxAoopd1zlqawO6iSabfftTRfDNFrcZhUs+mxpDDGMwFsZJHFNfnbRItd7VirQ+gI/bD2zTAjptR34xys9UJ/ESfqG1m+kg2bL/PtPqKZhrkmA2+qNKMS8JfUUnhqj2IpYmJXRyAZNvTz7SgVz5s1BVHfndKLryviWjaE/627L0Q2k0IcfotR7zhO+QTBGIe2WUyzzgUnJkgLcP2nOwCZLyr4AszCP17oK6VuXPLBxWWosxNQNLj4afDJreA+ud04jBf8HXfpOFm1aRq6BhmGi8UVIsHaoCr+GIMcYdI5dfTvWv0A//OPjH71Oahq2WhuVWwJD5YNO73URXqkGcdsj8s5wqBLyP0VhmvcK4iAFblL4sGF+UfvCG7q0NGjRiwishBV3opDgmKqBVNOuV92yQy0BbtJq2XtfpHPXhPST8RIKgpKv2u2o/YIfw2tNhhD4AB3XlqQ+b7ygrzDRKxztf6T1KQf4lUlHa81xdRG2qwrFpgZripJNUjH0ngNO1P/ImmhcrejBXG2zCzeeBW9syMu6K1m9SjUrydx1nR4YNFXg/6Aiirm9J2jM2HFopvZvtw+vNYzXCVGSWuvZaClIDEn/d1jyAaRvEHrm5NwBsq3uat8SFD+emgzwritQ=
  distributions: "sdist bdist_wheel" 

